### ISSUE TITLE
What requirements does the Spitfire .dll have to run.

### ISSUE THREAD

**Issue by SyntaxWarrior** [RainwayApp/spitfire#15]
Hi!
I've gotten spitfire to run on my computer, and am able to connect with multiple clients and the communication works. I would however like to deploy this to a separate machine to run continously. This is however proving quite difficult.

I keep getting the below error. 

So my question is, **what dependencies does Spitfire have**, why would I be seeing that error on several other machines (tried 2 windows 10 machines, and one windows server 2016 machine) when it runs perfectly fine on my Windows 10 development machine. 

I can create a build release on my windows 10 machine, copy that folder to any location on my dev machine and run it just fine. The same folder/build fails on any other machine I've tried with the below error.

Something must be missing.

I created a stackoverflow question about it here: https://stackoverflow.com/questions/53161400/cant-read-dll-on-production-server-but-works-on-dev-machine but no one has yet been able to help me find a solution.

> System.IO.FileNotFoundException: Could not load file or assembly 'Spitfire.dll' or one of its dependencies. The specified module could not be found.
> File name: 'Spitfire.dll'
>    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
>    at Owin.Loader.DefaultLoader.AssemblyDirScanner.<GetEnumerator>d__1e.MoveNext()
>    at Owin.Loader.DefaultLoader.SearchForStartupAttribute(String friendlyName, IList`1 errors, Boolean& conflict)
>    at Owin.Loader.DefaultLoader.GetDefaultConfiguration(String friendlyName, IList`1 errors)
>    at Owin.Loader.DefaultLoader.LoadImplementation(String startupName, IList`1 errorDetails)
>    at Owin.Loader.DefaultLoader.Load(String startupName, IList`1 errorDetails)
>    at Microsoft.Owin.Hosting.Engine.HostingEngine.ResolveApp(StartContext context)
>    at Microsoft.Owin.Hosting.Engine.HostingEngine.Start(StartContext context)
>    at Microsoft.Owin.Hosting.Starter.HostingStarter.Start(StartOptions options)
>    at Communication.WebRTC.WebRTCHandshaker.WebRTCLoop(String url) in F:\SW\DedicatedServer\Communication\WebRTC\WebRTCHandshaker.cs:line 56

Thank you for the help!

**Comment by SyntaxWarrior** [comment]
The problem was missing VC++ redistributable. After installing vc_redist.x64.exe everything worked.
